"""empty message

Revision ID: 71a42cb85d08
Revises: c305770046c2
Create Date: 2019-04-18 17:10:38.609999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71a42cb85d08'
down_revision = 'c305770046c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('biography', sa.String(length=80), nullable=True))
    op.add_column('user_profiles', sa.Column('email', sa.String(length=80), nullable=True))
    op.add_column('user_profiles', sa.Column('firstname', sa.String(length=80), nullable=True))
    op.add_column('user_profiles', sa.Column('joined_on', sa.Date(), nullable=True))
    op.add_column('user_profiles', sa.Column('lastname', sa.String(length=80), nullable=True))
    op.add_column('user_profiles', sa.Column('location', sa.String(length=80), nullable=True))
    op.add_column('user_profiles', sa.Column('password', sa.String(length=80), nullable=True))
    op.add_column('user_profiles', sa.Column('profile_photo', sa.String(length=80), nullable=True))
    op.create_unique_constraint(None, 'user_profiles', ['email'])
    op.drop_column('user_profiles', 'last_name')
    op.drop_column('user_profiles', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('first_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('last_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_profiles', type_='unique')
    op.drop_column('user_profiles', 'profile_photo')
    op.drop_column('user_profiles', 'password')
    op.drop_column('user_profiles', 'location')
    op.drop_column('user_profiles', 'lastname')
    op.drop_column('user_profiles', 'joined_on')
    op.drop_column('user_profiles', 'firstname')
    op.drop_column('user_profiles', 'email')
    op.drop_column('user_profiles', 'biography')
    # ### end Alembic commands ###
